import netToolboxPreview from '../assets/net-toolbox.mp4';
import kawaiiThemePreview from '../assets/kawaii-theme.mp4';
import toolsPortalPreview from '../assets/tools-portal.mp4';
import codeFlowchartPreview from '../assets/code-flowchart.mp4';
import particleLabPreview from '../assets/particle-lab.mp4';
import roughChartPreview from '../assets/rough-chart.mp4';
import towerGamePreview from '../assets/tower-game.mp4';
import algoVisualizerPreview from '../assets/algo-visualizer.mp4';
import { Project } from '../types/project';
import { SLIDE_IDS } from './slideIds';

export const projectsData: Project[] = [
  {
    id: SLIDE_IDS.ALGO_VISUALIZER,
    name: 'Algo Visualizer',
    title: 'Algo Visualizer',
    preview: algoVisualizerPreview,
    position: { x: 1500, y: 0, z: 0, rotateY: 0 },
    description:
      '交互式算法可视化工具：支持排序算法和路径查找算法的动态演示与教学',
    descriptionEn:
      'Interactive algorithm visualization tool with sorting and pathfinding animations',
    tech: ['Algorithm', 'Canvas', 'Visualization', 'Education'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/algo-visualizer/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/algo-visualizer', text: 'Github', githubRepo: 'watermelontip/algo-visualizer' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.CODE_FLOWCHART,
    name: 'Code Flowchart',
    title: 'Code Flowchart',
    preview: codeFlowchartPreview,
    position: { x: 1200, y: 800, z: 200, rotateY: 30 },
    description:
      '代码转流程图工具：将代码自动解析并生成可视化的 SVG 流程图',
    descriptionEn:
      'Convert code into visual SVG flowcharts automatically',
    tech: ['Parser', 'SVG', 'Code', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/code-flowchart/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/code-flowchart', text: 'Github', githubRepo: 'watermelontip/code-flowchart' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.PARTICLE_LAB,
    name: 'Particle Lab',
    title: 'Particle Lab',
    preview: particleLabPreview,
    position: { x: 0, y: 1500, z: 400, rotateY: 90 },
    description:
      '交互式粒子特效生成器：自由调节参数，实时预览各种酷炫粒子动画效果',
    descriptionEn:
      'Interactive particle effect generator with real-time parameter tuning',
    tech: ['Canvas', 'Animation', 'Particle', 'Creative'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/particle-lab/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/particle-lab', text: 'Github', githubRepo: 'watermelontip/particle-lab' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.ROUGH_CHART,
    name: 'Rough Chart',
    title: 'Rough Chart',
    preview: roughChartPreview,
    position: { x: -1060, y: 1060, z: 600, rotateY: 135 },
    description:
      '手绘风格图表生成器：基于 RoughViz，生成具有手绘质感的数据可视化图表',
    descriptionEn:
      'Hand-drawn style chart generator based on RoughViz',
    tech: ['Chart', 'RoughViz', 'SVG', 'Data Viz'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/rough-chart/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/rough-chart', text: 'Github', githubRepo: 'watermelontip/rough-chart' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.TOWER_GAME,
    name: 'Tower Game',
    title: 'Tower Game',
    preview: towerGamePreview,
    position: { x: -1500, y: 0, z: 800, rotateY: 180 },
    description:
      '堆塔小游戏：经典的堆叠方块游戏，考验你的反应和节奏感',
    descriptionEn:
      'Classic tower stacking game testing your timing and rhythm',
    tech: ['Game', 'Canvas', 'Animation', 'Casual'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/tower-game/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/tower-game', text: 'Github', githubRepo: 'watermelontip/tower-game' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.NET_TOOLBOX,
    name: 'Net Toolbox',
    title: 'Net Toolbox',
    preview: netToolboxPreview,
    position: { x: -1060, y: -1060, z: 1000, rotateY: 225 },
    description:
      '综合网络工具箱：IP 查询、延迟测试、DNS 查询、Whois、SSL 检测等 8 大功能',
    descriptionEn:
      'Comprehensive network toolbox: IP lookup, latency test, DNS, Whois, SSL detection and more',
    tech: ['Network', 'Vue', 'API', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/net-toolbox/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/net-toolbox', text: 'Github', githubRepo: 'watermelontip/net-toolbox' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.KAWAII_THEME,
    name: 'Kawaii AI Theme Engine',
    title: 'Kawaii AI Theme Engine',
    preview: kawaiiThemePreview,
    position: { x: 0, y: -1500, z: 1200, rotateY: 270 },
    description:
      '基于随机化的 AI 卡哇伊风格主题生成引擎，每次生成独一无二的可爱主题',
    descriptionEn:
      'Randomization-based AI kawaii-style theme generation engine',
    tech: ['AI', 'CSS', 'Theme', 'Generator'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/Kawaii-AI-Theme-Engine/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/Kawaii-AI-Theme-Engine', text: 'Github', githubRepo: 'watermelontip/Kawaii-AI-Theme-Engine' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.TOOLS_PORTAL,
    name: 'Tools Portal',
    title: 'Tools Portal',
    preview: toolsPortalPreview,
    position: { x: 1060, y: -1060, z: 1400, rotateY: 315 },
    description:
      '免费在线开发者工具箱：JSON 格式化、Base64、颜色转换、正则测试、QR 码、渐变生成等 21 个工具',
    descriptionEn:
      'Free online developer toolbox: JSON, Base64, color converter, regex, QR code, gradient generator and 21 tools',
    tech: ['Vue', 'CDN', 'Tools', 'Static'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/tools-portal-cdn/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/tools-portal-cdn', text: 'Github', githubRepo: 'watermelontip/tools-portal-cdn' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.TOKENSCOPE,
    name: 'TokenScope',
    title: 'TokenScope',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: 900, y: 1600, z: 200, rotateY: -20 },
    description:
      'AI Token 可视化工具：实时 token 计数 + 多模型成本对比 + 视觉热力图 + 优化建议',
    descriptionEn:
      'AI Token visualization: real-time counting, multi-model cost comparison, visual heatmap, optimization tips',
    tech: ['React', 'Vite', 'AI', 'Token'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/tokenscope/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/tokenscope', text: 'Github', githubRepo: 'watermelontip/tokenscope' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.CRONCRAFT,
    name: 'CronCraft',
    title: 'CronCraft',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: 600, y: 2400, z: 200, rotateY: 20 },
    description:
      '可视化 Cron 表达式编辑器：实时预览执行计划 + 20+ 预设模板 + 中文描述',
    descriptionEn:
      'Visual Cron expression editor: real-time execution preview, 20+ presets, Chinese support',
    tech: ['React', 'Vite', 'Cron', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/croncraft/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/croncraft', text: 'Github', githubRepo: 'watermelontip/croncraft' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.JSONTOTS,
    name: 'JsonToTS',
    title: 'JsonToTS',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: 300, y: 3200, z: 200, rotateY: -15 },
    description:
      'JSON 转 TypeScript 工具：实时转换 + 嵌套支持 + 自定义选项',
    descriptionEn:
      'JSON to TypeScript converter: real-time conversion, nested support, customizable options',
    tech: ['React', 'Vite', 'TypeScript', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/json-to-ts/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/json-to-ts', text: 'Github', githubRepo: 'watermelontip/json-to-ts' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.MARKPDF,
    name: 'MarkPDF',
    title: 'MarkPDF',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: 0, y: 4000, z: 200, rotateY: 10 },
    description:
      'Markdown 转 PDF 工具：实时预览 + 多种主题 + 一键导出',
    descriptionEn:
      'Markdown to PDF converter: real-time preview, multiple themes, one-click export',
    tech: ['React', 'Vite', 'Markdown', 'PDF'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/markpdf/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/markpdf', text: 'Github', githubRepo: 'watermelontip/markpdf' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.SCHEMAVIZ,
    name: 'SchemaViz',
    title: 'SchemaViz',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: -300, y: 4800, z: 200, rotateY: -10 },
    description:
      'JSON Schema 可视化工具：交互式树形图 + 类型高亮 + 节点详情',
    descriptionEn:
      'JSON Schema visualizer: interactive tree view, color-coded types, node details',
    tech: ['React', 'Vite', 'JSON', 'Schema'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/schema-viz/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/schema-viz', text: 'Github', githubRepo: 'watermelontip/schema-viz' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.GRIDFORGE,
    name: 'GridForge',
    title: 'GridForge',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: -600, y: 5600, z: 200, rotateY: 15 },
    description:
      'CSS Grid 生成器：可视化编辑 + 实时预览 + 模板库 + 代码导出',
    descriptionEn:
      'CSS Grid generator: visual editing, real-time preview, template library, code export',
    tech: ['React', 'Vite', 'CSS', 'Grid'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/grid-forge/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/grid-forge', text: 'Github', githubRepo: 'watermelontip/grid-forge' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.JSONTOCSV,
    name: 'JsonToCSV',
    title: 'JsonToCSV',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: -900, y: 6400, z: 200, rotateY: -20 },
    description:
      'JSON 转 CSV 工具：实时转换 + 嵌套支持 + 自定义选项 + 下载导出',
    descriptionEn:
      'JSON to CSV converter: real-time conversion, nested support, custom options, download export',
    tech: ['React', 'Vite', 'JSON', 'CSV'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/json-to-csv/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/json-to-csv', text: 'Github', githubRepo: 'watermelontip/json-to-csv' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.YAMLFORGE,
    name: 'YamlForge',
    title: 'YamlForge',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: -1200, y: 7200, z: 200, rotateY: 10 },
    description:
      'YAML ↔ JSON 双向转换工具：实时预览 + 语法高亮 + 格式化',
    descriptionEn:
      'YAML/JSON bidirectional converter: real-time preview, syntax highlighting, formatting',
    tech: ['React', 'Vite', 'YAML', 'JSON'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/yaml-forge/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/yaml-forge', text: 'Github', githubRepo: 'watermelontip/yaml-forge' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.BASE64FORGE,
    name: 'Base64Forge',
    title: 'Base64Forge',
    preview: algoVisualizerPreview, // Reuse preview for now
    position: { x: -1500, y: 8000, z: 200, rotateY: -15 },
    description:
      'Base64 编码/解码工具：文本/文件编码 + 图片预览 + 一键复制',
    descriptionEn:
      'Base64 encoder/decoder: text/file encoding, image preview, one-click copy',
    tech: ['React', 'Vite', 'Base64', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/base64-forge/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/base64-forge', text: 'Github', githubRepo: 'watermelontip/base64-forge' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.URLFORGE,
    name: 'UrlForge',
    title: 'UrlForge',
    preview: algoVisualizerPreview,
    position: { x: -1800, y: 8800, z: 200, rotateY: 20 },
    description: 'URL 编码/解码工具：双向转换 + URL 解析 + 查询参数解析',
    descriptionEn: 'URL encoder/decoder: bidirectional conversion, URL parsing, query parameter parsing',
    tech: ['React', 'Vite', 'URL', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/url-forge/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/url-forge', text: 'Github', githubRepo: 'watermelontip/url-forge' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.COLORCONVERT,
    name: 'ColorConvert',
    title: 'ColorConvert',
    preview: algoVisualizerPreview,
    position: { x: -2100, y: 9600, z: 200, rotateY: -10 },
    description: '颜色格式转换工具：HEX/RGB/HSL 互转 + 色彩调色板',
    descriptionEn: 'Color format converter: HEX/RGB/HSL conversion + color palette',
    tech: ['React', 'Vite', 'Color', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/color-convert/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/color-convert', text: 'Github', githubRepo: 'watermelontip/color-convert' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.TABLEFORGE,
    name: 'TableForge',
    title: 'TableForge',
    preview: algoVisualizerPreview,
    position: { x: -2400, y: 10400, z: 200, rotateY: 15 },
    description: 'Markdown 表格生成器：可视化编辑 + 实时预览 + 对齐控制',
    descriptionEn: 'Markdown table generator: visual editor, real-time preview, alignment control',
    tech: ['React', 'Vite', 'Markdown', 'Table'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/table-forge/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/table-forge', text: 'Github', githubRepo: 'watermelontip/table-forge' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.JSONDIFF,
    name: 'JsonDiff',
    title: 'JsonDiff',
    preview: algoVisualizerPreview,
    position: { x: -2700, y: 11200, z: 200, rotateY: -10 },
    description: 'JSON 差异比较工具：可视化差异 + 新增/删除/修改标记',
    descriptionEn: 'JSON diff comparison tool: visual diff with add/remove/change markers',
    tech: ['React', 'Vite', 'JSON', 'Diff'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/json-diff/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/json-diff', text: 'Github', githubRepo: 'watermelontip/json-diff' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.MARKPREVIEW,
    name: 'MarkPreview',
    title: 'MarkPreview',
    preview: algoVisualizerPreview,
    position: { x: -3000, y: 12000, z: 200, rotateY: 20 },
    description: 'Markdown 实时预览器：边写边看 + 分屏视图',
    descriptionEn: 'Markdown real-time previewer: split-pane view with live rendering',
    tech: ['React', 'Vite', 'Markdown', 'Preview'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/mark-preview/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/mark-preview', text: 'Github', githubRepo: 'watermelontip/mark-preview' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.REGEXLAB,
    name: 'RegexLab',
    title: 'RegexLab',
    preview: algoVisualizerPreview,
    position: { x: -3300, y: 12800, z: 200, rotateY: -15 },
    description: '正则表达式测试器：实时匹配 + 高亮显示 + 常用模式库',
    descriptionEn: 'Regex tester: real-time matching, highlighting, common patterns',
    tech: ['React', 'Vite', 'Regex', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/regex-lab/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/regex-lab', text: 'Github', githubRepo: 'watermelontip/regex-lab' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.JSONPRETTIFY,
    name: 'JsonPrettify',
    title: 'JsonPrettify',
    preview: algoVisualizerPreview,
    position: { x: -3600, y: 13600, z: 200, rotateY: 10 },
    description: 'JSON 格式化/压缩工具：美化 + 压缩 + 验证 + 统计',
    descriptionEn: 'JSON prettify/minify tool: beautify, minify, validate, stats',
    tech: ['React', 'Vite', 'JSON', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/json-prettify/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/json-prettify', text: 'Github', githubRepo: 'watermelontip/json-prettify' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.CHECKLIST,
    name: 'CheckList',
    title: 'CheckList',
    preview: algoVisualizerPreview,
    position: { x: -3900, y: 14400, z: 200, rotateY: -20 },
    description: 'Markdown 清单管理器：可视化任务管理 + 进度条 + 导出',
    descriptionEn: 'Markdown checklist manager: visual task management, progress bar, export',
    tech: ['React', 'Vite', 'Markdown', 'Todo'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/check-list/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/check-list', text: 'Github', githubRepo: 'watermelontip/check-list' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.EMOJIPICKER,
    name: 'EmojiPicker',
    title: 'EmojiPicker',
    preview: algoVisualizerPreview,
    position: { x: -4200, y: 15200, z: 200, rotateY: 10 },
    description: 'Emoji 选择器：搜索 + 分类浏览 + 一键复制',
    descriptionEn: 'Emoji picker: search, category browsing, one-click copy',
    tech: ['React', 'Vite', 'Emoji', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/emoji-picker/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/emoji-picker', text: 'Github', githubRepo: 'watermelontip/emoji-picker' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.QUOTEGEN,
    name: 'QuoteGen',
    title: 'QuoteGen',
    preview: algoVisualizerPreview,
    position: { x: -4500, y: 16000, z: 200, rotateY: -15 },
    description: '引言图片生成器：8 种主题 + 下载图片 + 复制文字',
    descriptionEn: 'Quote image generator: 8 themes, download, copy text',
    tech: ['React', 'Vite', 'Canvas', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/quote-gen/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/quote-gen', text: 'Github', githubRepo: 'watermelontip/quote-gen' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.LINKEXTRACT,
    name: 'LinkExtract',
    title: 'LinkExtract',
    preview: algoVisualizerPreview,
    position: { x: -4800, y: 16800, z: 200, rotateY: 20 },
    description: '链接提取器：从文本提取 URL/邮箱/Markdown 链接',
    descriptionEn: 'Link extractor: extract URLs, emails, Markdown links from text',
    tech: ['React', 'Vite', 'Parser', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/link-extract/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/link-extract', text: 'Github', githubRepo: 'watermelontip/link-extract' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.WORDCOUNTER,
    name: 'WordCounter',
    title: 'WordCounter',
    preview: algoVisualizerPreview,
    position: { x: -5100, y: 17600, z: 200, rotateY: -10 },
    description: '字数统计器：中英文统计 + 阅读时间 + 朗读时间',
    descriptionEn: 'Word counter: Chinese/English stats, reading time, speaking time',
    tech: ['React', 'Vite', 'Analytics', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/word-counter/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/word-counter', text: 'Github', githubRepo: 'watermelontip/word-counter' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.IMAGEGALLERY,
    name: 'ImageGallery',
    title: 'ImageGallery',
    preview: algoVisualizerPreview,
    position: { x: -5400, y: 18400, z: 200, rotateY: 15 },
    description: '图片画廊：瀑布流布局 + 灯箱预览',
    descriptionEn: 'Image gallery: waterfall layout, lightbox preview',
    tech: ['React', 'Vite', 'Gallery', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/image-gallery/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/image-gallery', text: 'Github', githubRepo: 'watermelontip/image-gallery' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.CODEHIGHLIGHT,
    name: 'CodeHighlight',
    title: 'CodeHighlight',
    preview: algoVisualizerPreview,
    position: { x: -5700, y: 19200, z: 200, rotateY: -20 },
    description: '代码高亮工具：7 种语言 + Prism.js + 实时预览',
    descriptionEn: 'Code highlight: 7 languages, Prism.js, real-time preview',
    tech: ['React', 'Vite', 'Prism', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/code-highlight/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/code-highlight', text: 'Github', githubRepo: 'watermelontip/code-highlight' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.TASKBOARD,
    name: 'TaskBoard',
    title: 'TaskBoard',
    preview: algoVisualizerPreview,
    position: { x: -6000, y: 20000, z: 200, rotateY: 10 },
    description: '看板任务板：拖拽式任务管理 + 优先级 + 状态流转',
    descriptionEn: 'Kanban task board: drag-drop, priority, status flow',
    tech: ['React', 'Vite', 'Kanban', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/task-board/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/task-board', text: 'Github', githubRepo: 'watermelontip/task-board' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.PASSWORDGEN,
    name: 'PasswordGen',
    title: 'PasswordGen',
    preview: algoVisualizerPreview,
    position: { x: -6300, y: 20800, z: 200, rotateY: -15 },
    description: '密码生成器：安全随机密码 + 强度检测 + 历史记录',
    descriptionEn: 'Password generator: secure random, strength detection, history',
    tech: ['React', 'Vite', 'Security', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/password-gen/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/password-gen', text: 'Github', githubRepo: 'watermelontip/password-gen' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.UUIDGEN,
    name: 'UuidGen',
    title: 'UuidGen',
    preview: algoVisualizerPreview,
    position: { x: -6600, y: 21600, z: 200, rotateY: 20 },
    description: 'UUID 生成器：批量生成 UUID/NanoID/ULID',
    descriptionEn: 'UUID generator: batch generate UUID, NanoID, ULID',
    tech: ['React', 'Vite', 'UUID', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/uuid-gen/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/uuid-gen', text: 'Github', githubRepo: 'watermelontip/uuid-gen' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.TIMESTAMPCONVERT,
    name: 'TimestampConvert',
    title: 'TimestampConvert',
    preview: algoVisualizerPreview,
    position: { x: -6900, y: 22400, z: 200, rotateY: -10 },
    description: '时间戳转换器：Unix 时间戳与日期互转 + 实时时钟',
    descriptionEn: 'Timestamp converter: Unix timestamp ↔ date, real-time clock',
    tech: ['React', 'Vite', 'Timestamp', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/timestamp-convert/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/timestamp-convert', text: 'Github', githubRepo: 'watermelontip/timestamp-convert' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.IPLOOKUP,
    name: 'IpLookup',
    title: 'IpLookup',
    preview: algoVisualizerPreview,
    position: { x: -7200, y: 23200, z: 200, rotateY: 15 },
    description: 'IP 查询工具：地理位置 + 网络信息 + 地图链接',
    descriptionEn: 'IP lookup: geolocation, network info, map link',
    tech: ['React', 'Vite', 'API', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/ip-lookup/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/ip-lookup', text: 'Github', githubRepo: 'watermelontip/ip-lookup' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.LOREMGEN,
    name: 'LoremGen',
    title: 'LoremGen',
    preview: algoVisualizerPreview,
    position: { x: -7500, y: 24000, z: 200, rotateY: -20 },
    description: 'Lorem Ipsum 占位文本生成器：Latin + 中文',
    descriptionEn: 'Lorem ipsum generator: Latin + Chinese',
    tech: ['React', 'Vite', 'Text', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/lorem-gen/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/lorem-gen', text: 'Github', githubRepo: 'watermelontip/lorem-gen' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.MARKDOWNCHEAT,
    name: 'MarkdownCheat',
    title: 'MarkdownCheat',
    preview: algoVisualizerPreview,
    position: { x: -7800, y: 24800, z: 200, rotateY: 10 },
    description: 'Markdown 速查表：常用语法参考 + 点击复制',
    descriptionEn: 'Markdown cheatsheet: syntax reference, click-to-copy',
    tech: ['React', 'Vite', 'Markdown', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/markdown-cheat/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/markdown-cheat', text: 'Github', githubRepo: 'watermelontip/markdown-cheat' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.CSSUNITS,
    name: 'CssUnits',
    title: 'CssUnits',
    preview: algoVisualizerPreview,
    position: { x: -8100, y: 25600, z: 200, rotateY: -15 },
    description: 'CSS 单位转换器：px/em/rem/%/vw/vh 互转',
    descriptionEn: 'CSS unit converter: px/em/rem/%/vw/vh conversion',
    tech: ['React', 'Vite', 'CSS', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/css-units/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/css-units', text: 'Github', githubRepo: 'watermelontip/css-units' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.HTMLENCODE,
    name: 'HtmlEncode',
    title: 'HtmlEncode',
    preview: algoVisualizerPreview,
    position: { x: -8400, y: 26400, z: 200, rotateY: 20 },
    description: 'HTML 实体编码器：编码/解码 + 常用实体参考',
    descriptionEn: 'HTML entity encoder: encode/decode, common entities reference',
    tech: ['React', 'Vite', 'HTML', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/html-encode/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/html-encode', text: 'Github', githubRepo: 'watermelontip/html-encode' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.BASECONVERT,
    name: 'BaseConvert',
    title: 'BaseConvert',
    preview: algoVisualizerPreview,
    position: { x: -8700, y: 27200, z: 200, rotateY: -10 },
    description: '进制转换器：二进制/八进制/十进制/十六进制互转',
    descriptionEn: 'Number base converter: binary/octal/decimal/hex',
    tech: ['React', 'Vite', 'Math', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/base-convert/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/base-convert', text: 'Github', githubRepo: 'watermelontip/base-convert' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.TEXTDIFF,
    name: 'TextDiff',
    title: 'TextDiff',
    preview: algoVisualizerPreview,
    position: { x: -9000, y: 28000, z: 200, rotateY: 15 },
    description: '文本对比工具：逐行差异 + LCS 算法 + 可视化增删改',
    descriptionEn: 'Text comparison: line diff, LCS algorithm, visual markers',
    tech: ['React', 'Vite', 'Diff', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/text-diff/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/text-diff', text: 'Github', githubRepo: 'watermelontip/text-diff' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.PALETTEGEN,
    name: 'PaletteGen',
    title: 'PaletteGen',
    preview: algoVisualizerPreview,
    position: { x: -9300, y: 28800, z: 200, rotateY: -20 },
    description: '调色板生成器：6 种色彩和谐 + 明度渐变',
    descriptionEn: 'Color palette generator: 6 harmonies, tint gradients',
    tech: ['React', 'Vite', 'Color', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/palette-gen/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/palette-gen', text: 'Github', githubRepo: 'watermelontip/palette-gen' },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.CSVTOTABLE,
    name: 'CsvToTable',
    title: 'CsvToTable',
    preview: algoVisualizerPreview,
    position: { x: -9600, y: 29600, z: 200, rotateY: 10 },
    description: 'CSV 转表格工具：CSV 转 Markdown/HTML 表格',
    descriptionEn: 'CSV to table converter: CSV to Markdown/HTML tables',
    tech: ['React', 'Vite', 'CSV', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/csv-to-table/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/csv-to-table', text: 'Github', githubRepo: 'watermelontip/csv-to-table' },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.LINECOUNTER,
    name: 'LineCounter',
    title: 'LineCounter',
    preview: algoVisualizerPreview,
    position: { x: -9900, y: 30400, z: 200, rotateY: -15 },
    description: '行数统计器：按文件类型统计代码/注释/空白行数',
    descriptionEn: 'Line counter: code/comment/blank lines by file type',
    tech: ['React', 'Vite', 'Analytics', 'Tool'],
    links: [
      { type: 'demo', url: 'https://watermelontip.github.io/line-counter/', text: 'Live Demo' },
      { type: 'code', url: 'https://github.com/watermelontip/line-counter', text: 'Github', githubRepo: 'watermelontip/line-counter' },
    ],
    layout: 'standard',
  },
];

export const mapData
  { id: SLIDE_IDS.TITLE, name: 'Introduction', icon: 'fas fa-home' },
  { id: SLIDE_IDS.ALGO_VISUALIZER, name: 'Algo Visualizer', icon: 'fas fa-project-diagram' },
  { id: SLIDE_IDS.CODE_FLOWCHART, name: 'Code Flowchart', icon: 'fas fa-sitemap' },
  { id: SLIDE_IDS.PARTICLE_LAB, name: 'Particle Lab', icon: 'fas fa-magic' },
  { id: SLIDE_IDS.ROUGH_CHART, name: 'Rough Chart', icon: 'fas fa-chart-bar' },
  { id: SLIDE_IDS.TOWER_GAME, name: 'Tower Game', icon: 'fas fa-gamepad' },
  { id: SLIDE_IDS.NET_TOOLBOX, name: 'Net Toolbox', icon: 'fas fa-network-wired' },
  { id: SLIDE_IDS.KAWAII_THEME, name: 'Kawaii Theme', icon: 'fas fa-palette' },
  { id: SLIDE_IDS.TOOLS_PORTAL, name: 'Tools Portal', icon: 'fas fa-tools' },
  { id: SLIDE_IDS.TOKENSCOPE, name: 'TokenScope', icon: 'fas fa-coins' },
  { id: SLIDE_IDS.COLORCONVERT, name: 'ColorConvert', icon: 'fas fa-palette' },
  { id: SLIDE_IDS.TABLEFORGE, name: 'TableForge', icon: 'fas fa-table' },
  { id: SLIDE_IDS.JSONDIFF, name: 'JsonDiff', icon: 'fas fa-code-branch' },
  { id: SLIDE_IDS.MARKPREVIEW, name: 'MarkPreview', icon: 'fas fa-eye' },
  { id: SLIDE_IDS.REGEXLAB, name: 'RegexLab', icon: 'fas fa-asterisk' },
  { id: SLIDE_IDS.JSONPRETTIFY, name: 'JsonPrettify', icon: 'fas fa-magic' },
  { id: SLIDE_IDS.CHECKLIST, name: 'CheckList', icon: 'fas fa-check-square' },
  { id: SLIDE_IDS.EMOJIPICKER, name: 'EmojiPicker', icon: 'fas fa-smile' },
  { id: SLIDE_IDS.QUOTEGEN, name: 'QuoteGen', icon: 'fas fa-quote-left' },
  { id: SLIDE_IDS.LINKEXTRACT, name: 'LinkExtract', icon: 'fas fa-link' },
  { id: SLIDE_IDS.WORDCOUNTER, name: 'WordCounter', icon: 'fas fa-font' },
  { id: SLIDE_IDS.IMAGEGALLERY, name: 'ImageGallery', icon: 'fas fa-images' },
  { id: SLIDE_IDS.CODEHIGHLIGHT, name: 'CodeHighlight', icon: 'fas fa-code' },
  { id: SLIDE_IDS.TASKBOARD, name: 'TaskBoard', icon: 'fas fa-columns' },
  { id: SLIDE_IDS.PASSWORDGEN, name: 'PasswordGen', icon: 'fas fa-key' },
  { id: SLIDE_IDS.UUIDGEN, name: 'UuidGen', icon: 'fas fa-fingerprint' },
  { id: SLIDE_IDS.TIMESTAMPCONVERT, name: 'TimestampConvert', icon: 'fas fa-clock' },
  { id: SLIDE_IDS.IPLOOKUP, name: 'IpLookup', icon: 'fas fa-globe' },
  { id: SLIDE_IDS.LOREMGEN, name: 'LoremGen', icon: 'fas fa-paragraph' },
  { id: SLIDE_IDS.MARKDOWNCHEAT, name: 'MarkdownCheat', icon: 'fas fa-book' },
  { id: SLIDE_IDS.CSSUNITS, name: 'CssUnits', icon: 'fas fa-ruler' },
  { id: SLIDE_IDS.HTMLENCODE, name: 'HtmlEncode', icon: 'fas fa-code' },
  { id: SLIDE_IDS.BASECONVERT, name: 'BaseConvert', icon: 'fas fa-calculator' },
  { id: SLIDE_IDS.TEXTDIFF, name: 'TextDiff', icon: 'fas fa-exchange-alt' },
  { id: SLIDE_IDS.PALETTEGEN, name: 'PaletteGen', icon: 'fas fa-palette' },
  { id: SLIDE_IDS.CSVTOTABLE, name: 'CsvToTable', icon: 'fas fa-table' },
  { id: SLIDE_IDS.LINECOUNTER, name: 'LineCounter', icon: 'fas fa-list-ol' },
  { id: SLIDE_IDS.OVERVIEW
  { id: SLIDE_IDS.MARKPDF, name: 'MarkPDF', icon: 'fas fa-file-pdf' },
  { id: SLIDE_IDS.SCHEMAVIZ, name: 'SchemaViz', icon: 'fas fa-sitemap' },
  { id: SLIDE_IDS.GRIDFORGE, name: 'GridForge', icon: 'fas fa-th' },
  { id: SLIDE_IDS.JSONTOCSV, name: 'JsonToCSV', icon: 'fas fa-file-csv' },
  { id: SLIDE_IDS.YAMLFORGE, name: 'YamlForge', icon: 'fas fa-exchange-alt' },
  { id: SLIDE_IDS.BASE64FORGE, name: 'Base64Forge', icon: 'fas fa-lock' },
  { id: SLIDE_IDS.OVERVIEW, name: 'Overview', icon: 'fas fa-th-large' },
];
